name: "Ansible Configuration - Unifi Controller"

on:
  push:
    paths:
      - "ansible/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  configure:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H <container-ip> >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini playbooks/install_unifi.yml
