name: "Terraform Deploy - Proxmox LXC"

on:
  push:
    paths:
      - "terraform/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize and Apply Terraform
        env:
          PROXMOX_HOST: ${{ secrets.PROXMOX_HOST }}
          PROXMOX_API_TOKEN_ID: ${{ secrets.PROXMOX_API_TOKEN_ID }}
          PROXMOX_API_TOKEN_SECRET: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
          PROXMOX_STORAGE_POOL: ${{ secrets.PROXMOX_STORAGE_POOL }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
